Opt into some Rails 7 defaults
Betterment/test_track pull request #196
Opened 2023-06-16 17:13 UTC by argvniyx-enroute

### Summary

> Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.

### Other Information

> If there's anything else that's important and relevant to your pull
request, mention that information here. This could include
benchmarks, or other information.

> Thanks for contributing to TestTrack!

/domain

2023-06-20 17:28 UTC, argvniyx-enroute commented
Had some time to put https://github.com/Betterment/test_track/pull/197 together. As with chronos, it seems only specs related to cookies broke, so we should be good. We can try to update to the defaults in a single PR or I can revert if we'd rather do it in two steps.

2023-06-21 13:00 UTC, effron requested changes
just a few minor questions, otherwise looks good!

2023-06-21 14:42 UTC, argvniyx-enroute commented on config/environments/test.rb
> +  config.cache_classes = ActiveRecord::Type::Boolean.new.cast(ENV.fetch('CACHE_CLASSES', '0'))
This is a slip on my part! Thanks for pointing it out.

2023-06-21 15:10 UTC, argvniyx-enroute commented on config/environments/production.rb
> +  config.active_support.report_deprecations = false
This comes straight from `rake app:update`.

2023-06-21 18:01 UTC, effron requested changes
just one really minor thing i missed on the first round. otherwise looks good!

2023-06-21 18:01 UTC, effron commented on config/application.rb
> +    config.active_support.cache_format_version = 7.0
we don't need this since it's part of `load_defaults 7.0`https://guides.rubyonrails.org/configuring.html#config-active-support-cache-format-version

2023-06-21 18:39 UTC, effron approved these changes
domainLGTM && platformLGTM!

2023-06-21 19:55 UTC, merged