Add Optional Environment Banner
Betterment/test_track pull request #212
Opened 2024-03-20 21:24 UTC by qcannon

### Summary

Currently, if an organization uses Test Track for multiple environments (e.g. production and stage), it can be a bit difficult to discern at first glance for which environment a user is managing a given split test.

This proposed change gives users the option to set a `DEPLOYMENT_ENV_LABEL` variable in the `.env` or `.env.local` file, which will subsequently be rendered in a bright red banner, like so:

![Screenshot 2024-03-20 at 5 23 52 PM](https://github.com/Betterment/test_track/assets/67171899/f273fb03-dd86-433d-bd7b-77268bf27ae5)

The banner is intentionally a tad obnoxious to make it glaringly obvious to the user which environment they are in. 

When no `DEPLOYMENT_ENV_LABEL` variable is set, the header renders as usual:

![Screenshot 2024-03-20 at 5 23 24 PM](https://github.com/Betterment/test_track/assets/67171899/fc01c995-b5d0-40ac-ac97-1421a725c449)

I envision organizations using the existing state for production and the banner state for a non-production environment (or perhaps vice-versa). 

/domain @Betterment/test_track_core

2024-03-20 21:37 UTC, smudge requested changes
Love it! 👏 

Any chance you can add a test for this? We have [this `with_env`](https://github.com/Betterment/test_track/blob/555c0d6a831c9395c7e3e03381c473426894c752/spec/support/environment_spec_helper.rb#L2) helper that allows us to change specific ENV vars on a per-example basis.

2024-03-20 22:00 UTC, qcannon commented
@smudge oh yes good call, and thank you for the tip on `with_env` helper! Pushed that change in https://github.com/Betterment/test_track/pull/212/commits/44389995ac4fce4bd6271f5a4db54e06c3482d95

2024-03-28 17:36 UTC, smudge commented on spec/requests/admin/split_details_spec.rb
> +    let(:default_app) { FactoryBot.create(:app, name: "default_app", auth_secret: "6Sd6T7T6Q8hKcoo0t8CTzV0IdN1EEHqXB2Ig4raZsOf") }
Do the tests pass without the `auth_secret` value passed? I'm wondering if this (fake, definitely fake! lol) auth secret is only necessary for API-based tests.

The `login_as` below should do the real auth for these requests.

2024-04-01 19:53 UTC, smudge approved these changes
domain LGTM && platform LGTM!

2024-04-01 19:53 UTC, merged